openapi: 3.0.1
info:
  title: AWS Serverless Demo API
  description: Demo material for the AWS Serverless Presentation
  version: 0.0.1
servers:
  - url: https://api.assertdevelopments.com/aws-serverless-demo
paths:
  /info:
    get:
      description: Get the build information
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
  /data:
    post:
      description: Forward data for processing
      requestBody:
        description: The data to be processed
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
      responses:
        201:
          description: Created
          headers:
            Location:
              schema:
                type: string
              description: Will contain an url referencing the created data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForwardDataResponse'
  /data/{id}:
    get:
      description: Get previously forwarded data
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The id of the data
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'

components:
  schemas:
    InfoResponse:
      properties:
        application:
          description: The name of the application
          example: "AWS Serverless Demo"
        description:
          description: The description of the application
          example: "Demo material for the AWS Serverless presentation"
        version:
          description: The version of the application
          example: "1.0"
    ForwardDataResponse:
      properties:
        message:
          description: The result
          example: "accepted payload with id 1642259669630"
    Data:
      properties:
        name:
          description: A name
          example: "Stefan"
