openapi: 3.0.1
info:
  title: AWS Serverless Demo API
  description: Demo material for the AWS Serverless Presentation
  version: 0.0.1
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.assertdevelopments.com/aws-serverless-demo
    description: test
paths:
  /info:
    get:
      description: Get the build information
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'

components:
  schemas:
    InfoResponse:
      properties:
        buildNumber:
          description: The build number
          example: "20210213T001642"
