service: aws-serverless-demo
frameworkVersion: ">=1.79.0"

package:
  patterns:
    - '!./**'
    - './src/*.js'

provider:
  name: aws
  region: 'eu-west-1'
  profile: 'stefan'
  stage: dev
  endpointType: regional
  deploymentBucket:
    name: assertdevelopments
  iam:
    role: AwsServerlessDemoLambdaRole
  versionFunctions: false

functions:
  info:
    name: info
    handler: src/info.handler
    runtime: nodejs14.x
    memorySize: 1024
    timeout: 10
    events:
      - http:
          path: /info
          method: GET

resources:
  - ${file(serverless/resources.yml)}

