service: aws-serverless-demo
frameworkVersion: ">=1.79.0"

package:
  exclude:
    - ./**
  include:
    - ./dist/api-bundle.js

provider:
  name: aws
  region: 'eu-west-1'
  profile: 'stefan'
  stage: dev
  endpointType: regional
  deploymentBucket:
    name: assertdevelopments
  role:
    Fn::GetAtt: [ AwsServerlessDemoLambdaRole, Arn ]
  versionFunctions: false
  logRetentionInDays: 7
  runtime: nodejs14.x

functions:
  aws-serverless-demo-api:
    name: aws-serverless-demo-api
    handler: dist/api-bundle.handler
    memorySize: 1024
    timeout: 2
    events:
      - http:
          path: /info
          method: get

resources:
  - ${file(serverless/resources.yml)}

