service: aws-serverless-demo
frameworkVersion: '>=2.37.2'
variablesResolutionMode: 20210326

package:
  patterns:
    - '!./**'
    - './src/*.js'

provider:
  name: aws
  region: 'eu-west-1'
  profile: 'stefan'
  stage: dev
  deploymentBucket:
    name: assertdevelopments
  iam:
    role: AwsServerlessDemoLambdaRole
  versionFunctions: false
  runtime: nodejs14.x
  memorySize: 1024
  timeout: 10

functions:
  info:
    name: info
    handler: src/info.handler
    events:
      - http:
          path: /info
          method: GET
  receiver:
    name: receiver
    handler: src/receiver.handler
    events:
      - http:
          path: /data
          method: POST
  downloader:
    name: downloader
    handler: src/downloader.handler
    events:
      - http:
          path: /data/{id}
          method: GET
  processor:
    name: processor
    handler: src/processor.handler
    events:
      - s3:
          bucket: aws-serverless-demo
          event: s3:ObjectCreated:*
          rules:
            - prefix: incoming/

resources:
  - ${file(serverless/resources.yml)}
